import sfhdgsd from '../../imgs/Products/10018_oVojqO0HUQ_oTMc70bUeYw.jpg';
import fgcxrej from '../../imgs/Products/10485_LJGXdzuvcmAJIpXkOK61FA.jpg';
import bvsdfhds from '../../imgs/Products/10489_JVg6h65iQHp_g6_NVER0-g.jpg';
import cbdetrdy from '../../imgs/Products/11735_T8uBuZKu8bR3XKalDKF82w.jpg';
import vxcijds from '../../imgs/Products/20730_XsCaKyvsuCxxeRpjLhebNg.jpg';
import ihtbsrg from '../../imgs/Products/29333_nB-qbFD-QGJ_zPxnbmVMCg.jpg';
import njuvbewuir from '../../imgs/Products/29430_01fUgtINn_6IYpBwmDZEXw.jpg';
import sasjdbfgyuas from '../../imgs/Products/42043_ptG02P2aRd73olzN9cvMwQ.jpg';
import sfhvusr from '../../imgs/Products/44044_A1dBpM9bRD-hDQz7IKmJww.jpg';
import sfhdgspkasdfd from '../../imgs/Products/51394_6R45tZVPa7QqnBz2tpUH1w.jpg';
import sfhdg00e93sd from '../../imgs/Products/51539_Qq133Agpgy56BIY3azi-tw.jpg';
import sfhdgs47d from '../../imgs/Products/51544_TZeW3kVicObuC8LKd12-fw.jpg';
import sfdgvsedhdgsd from '../../imgs/Products/57687_-No8SPGQDlTvaLVOZyq7hA.jpg';
import sfhdgdfghesd from '../../imgs/Products/78230_nRlF9XFVq6pOFOUJUgO9-A.jpg';
import werbvinsk from '../../imgs/Products/shadow.jpg';
import Mer921 from '../../imgs/Products/Mer921_gdAQ1_Mq1IJ6eTYQIP07lg.jpg';
import mer767 from '../../imgs/Products/mer76723_O4mm3IOi0tDvfQJ7597_eg.jpg';
import mer662 from '../../imgs/Products/mer66235_fewoF6XgxwTPWB71dcWiJA.jpg';
import Mer103 from '../../imgs/Products/Mer10340_GAt-fs5WIbbBDpRnpIXFcA.jpg';
import Mer274 from '../../imgs/Products/Mer27402_mb5R1U965SeBXDs7ywbnaA.jpg';
import Mer431 from '../../imgs/Products/Mer43186_bWVihBq081avC0nTAgQkBw.jpg';
import Mer436 from '../../imgs/Products/Mer43614_jrR52GE0S6fNhVgdiPrWjA.jpg';
import Mer463 from '../../imgs/Products/Mer46361_aUFEKy2sFmTSS3xJjFZOGA.jpg';
import Mer475 from '../../imgs/Products/Mer47541_fNQwiA-8kR5Dtq-ANu2KfQ.jpg';
import Mer718 from '../../imgs/Products/Mer71812_Rt7wr7Vgcq_7Rw4PL1gJYg.jpg';
import Mer639 from '../../imgs/Products/Mer63935_6CWgsn86oQskAIfJ-DN6sA.jpg';

const Data = [
  {
    id: "4760081600037",
    Salonid: "1",
    vip: "1",
    prem: " 1",
    Verified: " 1",
    Auction: " 1",
    Phone: "43535883",
    Model: "M3 ",
    Marka: "Bmw",
    Price: "30000",
    year: "2000",
    Ban: "fdfd",
    strPrice: "100.0",
    color: "Qara",
    HP: "500",
    litr: "3L",
    Km: "3000000",
    shassi: "45345343783",
    transmitter: "front",
    Condition: "2.5",
    Suret: "Suret",
    created_at: "11.05.2020",
    location: "Baku",
    Yanacaq: "Yanacaq",
    to_up: "Active",
    People: "8+ People",
    Button: "1",
    imgM: Mer921,
    img: {
      ImgS: Mer921,
      Imge: mer767,
      Imgf: mer662,
      Imgg: Mer103,
      Imgc: Mer274,
      Imgk: Mer431,
      Imgb: Mer436,
      Imgd: Mer463,
      Imgh: Mer475,
      Imgj: Mer718,
      Imgv: Mer639,
    },
    desc: "Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.",
  },
  {
    id: "2",
    Salonid: "1",
    vip: "1",
    prem: " 1",
    to_up: " 1",
    Verified: " 1",
    Auction: " 1",
    Phone: "43535883",
    Model: "M3",
    Marka: "Bmw",
    Price: "30000",
    year: "2000",
    Ban: "fdfd",
    strPrice: "100.0",
    color: "dfsf",
    HP: "500",
    litr: "3L",
    Km: "3000000",
    shassi: "NULL",
    transmitter: "front",
    Condition: "3",
    Suret: "Suret",
    created_at: "11.05.2020",
    location: "Baku",
    Yanacaq: "Yanacaq",
    People: "5 People",
    Button: "1",
    imgM: sfhdgsd,
    img: {
      Simg: Mer921,
      Img: mer767,
      Img: mer662,
      Img: Mer103,
      Img: Mer274,
      Img: Mer431,
      Img: Mer436,
      Img: Mer463,
      Img: Mer475,
      Img: Mer718,
      Img: Mer639,
    },
    desc: "Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.",
  },
  {
    id: "3",
    Phone: "43535883",
    Salonid: "1",
    vip: "1",
    prem: " 1",
    to_up: " 1",
    Verified: " 1",
    Auction: " 1",
    Model: "M3 ",
    Marka: "Audi",
    Price: "30000",
    year: "2000",
    Ban: "fdfd",
    strPrice: "100.0",
    color: "dfsf",
    HP: "500",
    litr: "3L",
    Km: "3000000",
    shassi: "NULL",
    transmitter: "front",
    Condition: "5",
    Suret: "Suret",
    created_at: "11.05.2020",
    location: "Gəncə",
    Yanacaq: "Yanacaq",
    to_up: "Active",
    People: "5 People",
    Button: "1",
    imgM: fgcxrej,
    img: {
      Simg: Mer921,
      Img: mer767,
      Img: mer662,
      Img: Mer103,
      Img: Mer274,
      Img: Mer431,
      Img: Mer436,
      Img: Mer463,
      Img: Mer475,
      Img: Mer718,
      Img: Mer639,
    },
    desc: "Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.",
  },
  {
    id: "4",
    Salonid: "1",
    vip: "1",
    prem: " 1",
    to_up: " 1",
    Verified: " 1",
    Auction: " 1",
    Phone: "43535883",
    Model: "M3 ",
    Marka: "Audi",
    Price: "30000",
    year: "2000",
    Ban: "fdfd",
    strPrice: "100.0",
    color: "dfsf",
    HP: "500",
    litr: "3L",
    Km: "3000000",
    shassi: "NULL",
    transmitter: "front",
    Condition: "5",
    Suret: "Suret",
    created_at: "11.05.2020",
    location: "Gəncə",
    Yanacaq: "Yanacaq",
    to_up: "Active",
    People: "5 People",
    Button: "1",
    imgM: bvsdfhds,
    img: {
      Simg: Mer921,
      Img: mer767,
      Img: mer662,
      Img: Mer103,
      Img: Mer274,
      Img: Mer431,
      Img: Mer436,
      Img: Mer463,
      Img: Mer475,
      Img: Mer718,
      Img: Mer639,
    },
    desc: "Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.",
  },
  {
    id: "5",
    Salonid: "1",
    vip: "1",
    prem: " 1",
    to_up: " 1",
    Verified: " 1",
    Auction: " 1",
    Phone: "43535883",
    Model: "M3 ",
    Marka: "Bmw",
    Price: "30000",
    year: "2000",
    Ban: "fdfd",
    strPrice: "100.0",
    color: "dfsf",
    HP: "500",
    litr: "3L",
    Km: "3000000",
    shassi: "NULL",
    transmitter: "front",
    Condition: "2.5",
    Suret: "Suret",
    created_at: "11.05.2020",
    location: "Baku",
    Yanacaq: "Yanacaq",
    to_up: "Active",
    People: "5 People",
    Button: "1",
    imgM: cbdetrdy,
    img: {
      Simg: Mer921,
      Img: mer767,
      Img: mer662,
      Img: Mer103,
      Img: Mer274,
      Img: Mer431,
      Img: Mer436,
      Img: Mer463,
      Img: Mer475,
      Img: Mer718,
      Img: Mer639,
    },
    desc: "Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.",
  },
  {
    id: "6",
    Salonid: "1",
    vip: "1",
    prem: " 1",
    to_up: " 1",
    Verified: " 1",
    Auction: " 1",
    Phone: "43535883",
    Model: "M3 ",
    Marka: "Bmw",
    Price: "30000",
    year: "2000",
    Ban: "fdfd",
    strPrice: "100.0",
    color: "dfsf",
    HP: "500",
    litr: "3L",
    Km: "3000000",
    shassi: "NULL",
    transmitter: "front",
    Condition: "2.5",
    Suret: "Suret",
    created_at: "11.05.2020",
    location: "Baku",
    Yanacaq: "Dizel",
    to_up: "Active",
    People: "5 People",
    Button: "1",
    imgM: vxcijds,
    img: {
      Simg: Mer921,
      Img: mer767,
      Img: mer662,
      Img: Mer103,
      Img: Mer274,
      Img: Mer431,
      Img: Mer436,
      Img: Mer463,
      Img: Mer475,
      Img: Mer718,
      Img: Mer639,
    },
    desc: "Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.",
  },
  {
    id: "7",
    Salonid: "1",
    vip: "1",
    prem: " 1",
    to_up: " 1",
    Verified: " 1",
    Auction: " 1",
    Phone: "43535883",
    Model: "M3 ",
    Marka: "Audi",
    Price: "30000",
    year: "2000",
    Ban: "fdfd",
    strPrice: "100.0",
    color: "dfsf",
    HP: "500",
    litr: "3L",
    Km: "3000000",
    shassi: "NULL",
    transmitter: "front",
    Condition: "2.5",
    Suret: "Suret",
    created_at: "11.05.2020",
    location: "Baku",
    Yanacaq: "Yanacaq",
    to_up: "Active",
    People: "5 People",
    Button: "1",
    imgM: ihtbsrg,
    img: {
      Simg: Mer921,
      Img: mer767,
      Img: mer662,
      Img: Mer103,
      Img: Mer274,
      Img: Mer431,
      Img: Mer436,
      Img: Mer463,
      Img: Mer475,
      Img: Mer718,
      Img: Mer639,
    },
    desc: "Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.",
  },
  {
    id: "8",
    Salonid: "1",
    vip: "1",
    prem: " 1",
    to_up: " 1",
    Verified: " 1",
    Auction: " 1",
    Phone: "43535883",
    Model: "A3 ",
    Marka: "Audi",
    Price: "30000",
    year: "2000",
    Ban: "fdfd",
    strPrice: "100.0",
    color: "dfsf",
    HP: "500",
    litr: "3L",
    Km: "3000000",
    shassi: "NULL",
    transmitter: "front",
    Condition: "2.5",
    Suret: "Suret",
    created_at: "11.05.2020",
    location: "Baku",
    Yanacaq: "Yanacaq",
    to_up: "Active",
    People: "5 People",
    Button: "1",
    imgM: njuvbewuir,
    img: {
      Simg: Mer921,
      Img: mer767,
      Img: mer662,
      Img: Mer103,
      Img: Mer274,
      Img: Mer431,
      Img: Mer436,
      Img: Mer463,
      Img: Mer475,
      Img: Mer718,
      Img: Mer639,
    },
    desc: "Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.",
  },
  {
    id: "9",
    Salonid: "1",
    vip: "1",
    prem: " 1",
    to_up: " 1",
    Verified: " 1",
    Auction: " 1",
    Phone: "43535883",
    Model: "M3 ",
    Marka: "Bmw",
    Price: "30000",
    year: "2000",
    Ban: "fdfd",
    strPrice: "100.0",
    color: "dfsf",
    HP: "500",
    litr: "3L",
    Km: "3000000",
    shassi: "NULL",
    transmitter: "front",
    Condition: "2.5",
    Suret: "Suret",
    created_at: "11.05.2020",
    location: "Lənkəran",
    Yanacaq: "Yanacaq",
    to_up: "Active",
    People: "5 People",
    Button: "1",
    imgM: sasjdbfgyuas,
    img: {
      Simg: Mer921,
      Img: mer767,
      Img: mer662,
      Img: Mer103,
      Img: Mer274,
      Img: Mer431,
      Img: Mer436,
      Img: Mer463,
      Img: Mer475,
      Img: Mer718,
      Img: Mer639,
    },
    desc: "Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.",
  },
  {
    id: "10",
    Salonid: "1",
    vip: "1",
    prem: " 1",
    to_up: " 1",
    Verified: " 1",
    Auction: " 1",
    Phone: "43535883",
    Model: "M3 ",
    Marka: "Bmw",
    Price: "30000",
    year: "2000",
    Ban: "fdfd",
    strPrice: "100.0",
    color: "dfsf",
    HP: "500",
    litr: "3L",
    Km: "3000000",
    shassi: "NULL",
    transmitter: "front",
    Condition: "2.5",
    Suret: "Suret",
    created_at: "11.05.2020",
    location: "Baku",
    Yanacaq: "Yanacaq",
    to_up: "Active",
    People: "5 People",
    Button: "1",
    imgM: sfhvusr,
    img: {
      Simg: Mer921,
      Img: mer767,
      Img: mer662,
      Img: Mer103,
      Img: Mer274,
      Img: Mer431,
      Img: Mer436,
      Img: Mer463,
      Img: Mer475,
      Img: Mer718,
      Img: Mer639,
    },
    desc: "Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.",
  },
  {
    id: "11",
    Salonid: "1",
    vip: "1",
    prem: " 1",
    to_up: " 1",
    Verified: " 1",
    Auction: " 1",
    Phone: "43535883",
    Model: "Pajero",
    Marka: "Mitsubishi",
    Price: "21 500",
    year: "2007",
    Ban: "Offroader / SUV",
    strPrice: "100.0",
    color: "Qara",
    HP: "189 a.g.",
    litr: "3.0L",
    Km: "183 000",
    shassi: "NULL",
    transmitter: "Tam",
    Condition: "4.8",
    Suret: "Avtomat",
    created_at: "11.05.2020",
    location: "Baku",
    Yanacaq: "Yanacaq",
    to_up: "Active",
    People: "5 People",
    Button: "1",
    imgM: sfhdgspkasdfd,
    img: {
      Simg: Mer921,
      Img: mer767,
      Img: mer662,
      Img: Mer103,
      Img: Mer274,
      Img: Mer431,
      Img: Mer436,
      Img: Mer463,
      Img: Mer475,
      Img: Mer718,
      Img: Mer639,
    },
    desc: "Avtomobıl yaxshı veziyyetdedir    Motor korobka ideal    Vuruq udar yoxdur    Texniki və elektroniki heç bir problemi yoxdur",
  },
  {
    id: "12",
    Salonid: "1",
    vip: "1",
    prem: " 1",
    to_up: " 1",
    Verified: " 1",
    Auction: " 1",
    Phone: "43535883",
    Model: "M3 ",
    Marka: "Bmw",
    Price: "30000",
    year: "2000",
    Ban: "fdfd",
    strPrice: "100.0",
    color: "dfsf",
    HP: "500",
    litr: "3L",
    Km: "3000000",
    shassi: "NULL",
    transmitter: "front",
    Condition: "2.5",
    Suret: "Suret",
    created_at: "11.05.2020",
    location: "Baku",
    Yanacaq: "Yanacaq",
    to_up: "Active",
    People: "5 People",
    Button: "1",
    imgM: sfhdg00e93sd,
    img: {
      Simg: Mer921,
      Img: mer767,
      Img: mer662,
      Img: Mer103,
      Img: Mer274,
      Img: Mer431,
      Img: Mer436,
      Img: Mer463,
      Img: Mer475,
      Img: Mer718,
      Img: Mer639,
    },
    desc: "Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.",
  },
  //ss//
  {
    id: "13",
    Salonid: "1",
    vip: "1",
    prem: " 1",
    to_up: " 1",
    Verified: " 1",
    Auction: " 1",
    Phone: "43535883",
    Model: "M3 ",
    Marka: "Bmw",
    Price: "30000",
    year: "2000",
    Ban: "fdfd",
    strPrice: "100.0",
    color: "dfsf",
    HP: "500",
    litr: "3L",
    Km: "3000000",
    shassi: "NULL",
    transmitter: "front",
    Condition: "2.5",
    Suret: "Suret",
    created_at: "11.05.2020",
    location: "Baku",
    Yanacaq: "Yanacaq",
    to_up: "Active",
    People: "5 People",
    Button: "1",
    imgM: sfhdgs47d,
    img: {
      Simg: Mer921,
      Img: mer767,
      Img: mer662,
      Img: Mer103,
      Img: Mer274,
      Img: Mer431,
      Img: Mer436,
      Img: Mer463,
      Img: Mer475,
      Img: Mer718,
      Img: Mer639,
    },
    desc: "Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.",
  },
  {
    id: "14",
    Salonid: "1",
    vip: "1",
    prem: " 1",
    to_up: " 1",
    Verified: " 1",
    Auction: " 1",
    Phone: "43535883",
    Model: "M3 ",
    Marka: "Bmw",
    Price: "30000",
    year: "2000",
    Ban: "fdfd",
    strPrice: "100.0",
    color: "dfsf",
    HP: "500",
    litr: "3L",
    Km: "3000000",
    shassi: "NULL",
    transmitter: "front",
    Condition: "2.5",
    Suret: "Suret",
    created_at: "11.05.2020",
    location: "Baku",
    Yanacaq: "Yanacaq",
    to_up: "Active",
    People: "5 People",
    Button: "1",
    imgM: sfdgvsedhdgsd,
    img: {
      ImgS: Mer921,
      Imge: mer767,
      Imgf: mer662,
      Imgg: Mer103,
      Imgc: Mer274,
      Imgk: Mer431,
      Imgb: Mer436,
      Imgd: Mer463,
      Imgh: Mer475,
      Imgj: Mer718,
      Imgv: Mer639,
    },
    desc: "Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.",
  },
  {
    id: "15",
    Salonid: "1",
    vip: "1",
    prem: " 1",
    to_up: " 1",
    Verified: " 1",
    Auction: " 1",
    Phone: "43535883",
    Model: "M3 ",
    Marka: "Audi",
    Price: "30000",
    year: "2000",
    Ban: "fdfd",
    strPrice: "100.0",
    color: "dfsf",
    HP: "500",
    litr: "3L",
    Km: "3000000",
    shassi: "NULL",
    transmitter: "front",
    Condition: "2.5",
    Suret: "Suret",
    created_at: "11.05.2020",
    location: "Baku",
    Yanacaq: "Yanacaq",
    to_up: "Active",
    People: "5 People",
    Button: "1",
    imgM: sfhdgdfghesd,
    img: {
      ImgS: Mer921,
      Imge: mer767,
      Imgf: mer662,
      Imgg: Mer103,
      Imgc: Mer274,
      Imgk: Mer431,
      Imgb: Mer436,
      Imgd: Mer463,
      Imgh: Mer475,
      Imgj: Mer718,
      Imgv: Mer639,
    },
    desc: "Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.",
  },
  {
    id: "16",
    // Salonid: "1",
    vip: "1",
    prem: " ",
    to_up: " 1",
    Verified: " 1",
    Auction: '0',
    Phone: "43535883",
    Model: "M3 ",
    Marka: "Bmw",
    Price: "30000",
    year: "2000",
    Ban: "fdfd",
    strPrice: "100.0",
    color: "dfsf",
    HP: "500",
    litr: "3L",
    Km: "3000000",
    shassi: "NULL",
    transmitter: "front",
    Condition: "2.5",
    Suret: "Suret",
    created_at: "11.05.2020",
    location: "Baku",
    Yanacaq: "Yanacaq",
    to_up: "Active",
    People: "5 People",
    Button: "1",
    imgM: werbvinsk,
    img: {
      ImgS: Mer921,
      Imge: mer767,
      Imgf: mer662,
      Imgg: Mer103,
      Imgc: Mer274,
      Imgk: Mer431,
      Imgb: Mer436,
      Imgd: Mer463,
      Imgh: Mer475,
      Imgj: Mer718,
      Imgv: Mer639,
    },
    desc: "Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.",
  },
];

export default Data;