import sfhdgsd from '../../imgs/ehtiyat-Imgs/1665332366187_bulletin.jpeg';
import fgcxrej from '../../imgs/ehtiyat-Imgs/1665340834431_bulletin.jpeg';
import bvsdfhds from '../../imgs/ehtiyat-Imgs/1665509448117_bulletin.jpeg';
import cbdetrdy from '../../imgs/ehtiyat-Imgs/1665529331946_bulletin.jpeg';
import Mer921 from '../../imgs/ehtiyat-Imgs/1665529501105_bulletin.jpeg';

const Data = [
    {
        id: "4760081600037",
        Phone: "43535883",
        title: "M3 ",
        category: "Bmw",
        price: "30000",
        year: "2000",
        Ban: "fdfd",
        strPrice: "100.0",
        color: "Qara",
        HP: "500",
        litr: "3L",
        Km: "3000000",
        shassi: "45345343783",
        transmitter: "front",
        Condition: "2.5",
        mekanik: "Mekanik",
        date: "11.05.2020",
        location: "Baku",
        Benzin: "Benzin",
        activity: "Active",
        people: "5 People",
        Button: "1",
        imgM: Mer921,
        // img: {
        //     ImgS: Mer921,
        //     Imge: mer767,
        //     Imgf: mer662,
        //     Imgg: Mer103,
        //     Imgc: Mer274,
        //     Imgk: Mer431,
        //     Imgb: Mer436,
        //     Imgd: Mer463,
        //     Imgh: Mer475,
        //     Imgj: Mer718,
        //     Imgv: Mer639,
        // },
        desc: "Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.",
    },
    {
        id: "2",
        Phone: "43535883",
        title: "M3",
        category: "Bmw",
        price: "30000",
        year: "2000",
        Ban: "fdfd",
        strPrice: "100.0",
        color: "dfsf",
        HP: "500",
        litr: "3L",
        Km: "3000000",
        shassi: "NULL",
        transmitter: "front",
        Condition: "3",
        mekanik: "Mekanik",
        date: "11.05.2020",
        location: "Baku",
        Benzin: "Benzin",
        activity: "Active",
        people: "5 People",
        Button: "1",
        imgM: sfhdgsd,
        // img: {
        //     Simg: Mer921,
        //     Img: mer767,
        //     Img: mer662,
        //     Img: Mer103,
        //     Img: Mer274,
        //     Img: Mer431,
        //     Img: Mer436,
        //     Img: Mer463,
        //     Img: Mer475,
        //     Img: Mer718,
        //     Img: Mer639,
        // },
        desc: "Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.",
    },
    {
        id: "3",
        Phone: "43535883",
        title: "M3 ",
        category: "Audi",
        price: "30000",
        year: "2000",
        Ban: "fdfd",
        strPrice: "100.0",
        color: "dfsf",
        HP: "500",
        litr: "3L",
        Km: "3000000",
        shassi: "NULL",
        transmitter: "front",
        Condition: "5",
        mekanik: "Mekanik",
        date: "11.05.2020",
        location: "Gəncə",
        Benzin: "Benzin",
        activity: "Active",
        people: "5 People",
        Button: "1",
        imgM: fgcxrej,
        // img: {
        //     Simg: Mer921,
        //     Img: mer767,
        //     Img: mer662,
        //     Img: Mer103,
        //     Img: Mer274,
        //     Img: Mer431,
        //     Img: Mer436,
        //     Img: Mer463,
        //     Img: Mer475,
        //     Img: Mer718,
        //     Img: Mer639,
        // },
        desc: "Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.",
    },
    {
        id: "4",
        Phone: "43535883",
        title: "M3 ",
        category: "Audi",
        price: "30000",
        year: "2000",
        Ban: "fdfd",
        strPrice: "100.0",
        color: "dfsf",
        HP: "500",
        litr: "3L",
        Km: "3000000",
        shassi: "NULL",
        transmitter: "front",
        Condition: "5",
        mekanik: "Mekanik",
        date: "11.05.2020",
        location: "Gəncə",
        Benzin: "Benzin",
        activity: "Active",
        people: "5 People",
        Button: "1",
        imgM: bvsdfhds,
        // img: {
        //     Simg: Mer921,
        //     Img: mer767,
        //     Img: mer662,
        //     Img: Mer103,
        //     Img: Mer274,
        //     Img: Mer431,
        //     Img: Mer436,
        //     Img: Mer463,
        //     Img: Mer475,
        //     Img: Mer718,
        //     Img: Mer639,
        // },
        desc: "Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.",
    },
    {
        id: "5",
        Phone: "43535883",
        title: "M3 ",
        category: "Bmw",
        price: "30000",
        year: "2000",
        Ban: "fdfd",
        strPrice: "100.0",
        color: "dfsf",
        HP: "500",
        litr: "3L",
        Km: "3000000",
        shassi: "NULL",
        transmitter: "front",
        Condition: "2.5",
        mekanik: "Mekanik",
        date: "11.05.2020",
        location: "Baku",
        Benzin: "Benzin",
        activity: "Active",
        people: "5 People",
        Button: "1",
        imgM: cbdetrdy,
        // img: {
        //     Simg: Mer921,
        //     Img: mer767,
        //     Img: mer662,
        //     Img: Mer103,
        //     Img: Mer274,
        //     Img: Mer431,
        //     Img: Mer436,
        //     Img: Mer463,
        //     Img: Mer475,
        //     Img: Mer718,
        //     Img: Mer639,
        // },
        desc: "Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.",
    },

];

export default Data;