import sfhdgsd from '../../imgs/Products/10018_oVojqO0HUQ_oTMc70bUeYw.jpg';
import fgcxrej from '../../imgs/Products/10485_LJGXdzuvcmAJIpXkOK61FA.jpg';
import bvsdfhds from '../../imgs/Products/10489_JVg6h65iQHp_g6_NVER0-g.jpg';
import cbdetrdy from '../../imgs/Products/11735_T8uBuZKu8bR3XKalDKF82w.jpg';
import Mer921 from '../../imgs/Products/Mer921_gdAQ1_Mq1IJ6eTYQIP07lg.jpg';
import mer767 from '../../imgs/Products/mer76723_O4mm3IOi0tDvfQJ7597_eg.jpg';
import mer662 from '../../imgs/Products/mer66235_fewoF6XgxwTPWB71dcWiJA.jpg';
import Mer103 from '../../imgs/Products/Mer10340_GAt-fs5WIbbBDpRnpIXFcA.jpg';
import Mer274 from '../../imgs/Products/Mer27402_mb5R1U965SeBXDs7ywbnaA.jpg';
import Mer431 from '../../imgs/Products/Mer43186_bWVihBq081avC0nTAgQkBw.jpg';
import Mer436 from '../../imgs/Products/Mer43614_jrR52GE0S6fNhVgdiPrWjA.jpg';
import Mer463 from '../../imgs/Products/Mer46361_aUFEKy2sFmTSS3xJjFZOGA.jpg';
import Mer475 from '../../imgs/Products/Mer47541_fNQwiA-8kR5Dtq-ANu2KfQ.jpg';
import Mer718 from '../../imgs/Products/Mer71812_Rt7wr7Vgcq_7Rw4PL1gJYg.jpg';
import Mer639 from '../../imgs/Products/Mer63935_6CWgsn86oQskAIfJ-DN6sA.jpg';

const Data = [
  {
    id: "4760081600037",
    Phone: "43535883",
    title: "M3 ",
    category: "Bmw",
    price: "30000",
    year: "2000",
    Ban: "fdfd",
    strPrice: "100.0",
    color: "Qara",
    HP: "500",
    litr: "3L",
    Km: "3000000",
    shassi: "45345343783",
    transmitter: "front",
    Condition: "2.5",
    mekanik: "Mekanik",
    date: "11.05.2020",
    location: "Baku",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    Button: "1",
    imgM: Mer921,
    img: {
      ImgS: Mer921,
      Imge: mer767,
      Imgf: mer662,
      Imgg: Mer103,
      Imgc: Mer274,
      Imgk: Mer431,
      Imgb: Mer436,
      Imgd: Mer463,
      Imgh: Mer475,
      Imgj: Mer718,
      Imgv: Mer639,
    },
    desc: "Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.",
  },
  {
    id: "2",
    Phone: "43535883",
    title: "M3",
    category: "Bmw",
    price: "30000",
    year: "2000",
    Ban: "fdfd",
    strPrice: "100.0",
    color: "dfsf",
    HP: "500",
    litr: "3L",
    Km: "3000000",
    shassi: "NULL",
    transmitter: "front",
    Condition: "3",
    mekanik: "Mekanik",
    date: "11.05.2020",
    location: "Baku",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    Button: "1",
    imgM: sfhdgsd,
    img: {
      Simg: Mer921,
      Img: mer767,
      Img: mer662,
      Img: Mer103,
      Img: Mer274,
      Img: Mer431,
      Img: Mer436,
      Img: Mer463,
      Img: Mer475,
      Img: Mer718,
      Img: Mer639,
    },
    desc: "Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.",
  },
  {
    id: "3",
    Phone: "43535883",
    title: "M3 ",
    category: "Audi",
    price: "30000",
    year: "2000",
    Ban: "fdfd",
    strPrice: "100.0",
    color: "dfsf",
    HP: "500",
    litr: "3L",
    Km: "3000000",
    shassi: "NULL",
    transmitter: "front",
    Condition: "5",
    mekanik: "Mekanik",
    date: "11.05.2020",
    location: "Gəncə",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    Button: "1",
    imgM: fgcxrej,
    img: {
      Simg: Mer921,
      Img: mer767,
      Img: mer662,
      Img: Mer103,
      Img: Mer274,
      Img: Mer431,
      Img: Mer436,
      Img: Mer463,
      Img: Mer475,
      Img: Mer718,
      Img: Mer639,
    },
    desc: "Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.",
  },
  {
    id: "4",
    Phone: "43535883",
    title: "M3 ",
    category: "Audi",
    price: "30000",
    year: "2000",
    Ban: "fdfd",
    strPrice: "100.0",
    color: "dfsf",
    HP: "500",
    litr: "3L",
    Km: "3000000",
    shassi: "NULL",
    transmitter: "front",
    Condition: "5",
    mekanik: "Mekanik",
    date: "11.05.2020",
    location: "Gəncə",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    Button: "1",
    imgM: bvsdfhds,
    img: {
      Simg: Mer921,
      Img: mer767,
      Img: mer662,
      Img: Mer103,
      Img: Mer274,
      Img: Mer431,
      Img: Mer436,
      Img: Mer463,
      Img: Mer475,
      Img: Mer718,
      Img: Mer639,
    },
    desc: "Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.",
  },
  {
    id: "5",
    Phone: "43535883",
    title: "M3 ",
    category: "Bmw",
    price: "30000",
    year: "2000",
    Ban: "fdfd",
    strPrice: "100.0",
    color: "dfsf",
    HP: "500",
    litr: "3L",
    Km: "3000000",
    shassi: "NULL",
    transmitter: "front",
    Condition: "2.5",
    mekanik: "Mekanik",
    date: "11.05.2020",
    location: "Baku",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    Button: "1",
    imgM: cbdetrdy,
    img: {
      Simg: Mer921,
      Img: mer767,
      Img: mer662,
      Img: Mer103,
      Img: Mer274,
      Img: Mer431,
      Img: Mer436,
      Img: Mer463,
      Img: Mer475,
      Img: Mer718,
      Img: Mer639,
    },
    desc: "Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.",
  },

];

export default Data;