import nRlssF9X from "../imgs/Products/87650_277VIOdLOszxsC2cAzgf6A.jpg";
import sfhdgsd from '../imgs/Products/10018_oVojqO0HUQ_oTMc70bUeYw.jpg';
import fgcxrej from '../imgs/Products/10485_LJGXdzuvcmAJIpXkOK61FA.jpg';
import bvsdfhds from '../imgs/Products/10489_JVg6h65iQHp_g6_NVER0-g.jpg';
import cbdetrdy from '../imgs/Products/11735_T8uBuZKu8bR3XKalDKF82w.jpg';
import vxcijds from '../imgs/Products/20730_XsCaKyvsuCxxeRpjLhebNg.jpg';
import ihtbsrg from '../imgs/Products/29333_nB-qbFD-QGJ_zPxnbmVMCg.jpg';
import njuvbewuir from '../imgs/Products/29430_01fUgtINn_6IYpBwmDZEXw.jpg';
import sasjdbfgyuas from '../imgs/Products/42043_ptG02P2aRd73olzN9cvMwQ.jpg';
import sfhvusr from '../imgs/Products/44044_A1dBpM9bRD-hDQz7IKmJww.jpg';
import sfhdgspkasdfd from '../imgs/Products/51394_6R45tZVPa7QqnBz2tpUH1w.jpg';
import sfhdg00e93sd from '../imgs/Products/51539_Qq133Agpgy56BIY3azi-tw.jpg';
import sfhdgs47d from '../imgs/Products/51544_TZeW3kVicObuC8LKd12-fw.jpg';
import sfdgvsedhdgsd from '../imgs/Products/57687_-No8SPGQDlTvaLVOZyq7hA.jpg';
import sfhdgdfghesd from '../imgs/Products/78230_nRlF9XFVq6pOFOUJUgO9-A.jpg';
import werbvinsk from '../imgs/Products/shadow.jpg';


const Data = [
  {
    id: "1",
    title: "M3 ",
    category: "Bmw",
    price: "30000",
    mekanik: "Mekanik",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    Button: "1",
    img: nRlssF9X,
    desc: "Sport",
  },
  {
    id: "2",
    title: "M3",
    category: "Bmw",
    price: "30000",
    mekanik: "Mekanik",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    Button: "1",
    img: sfhdgsd,
    desc: "Sport",
  },
  {
    id: "3",
    title: "M3 ",
    category: "Audi",
    price: "30000",
    mekanik: "Mekanik",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    Button: "1",
    img: fgcxrej,
    desc: "Sport",
  },
  {
    id: "4",
    title: "M3 ",
    category: "merco",
    price: "250",
    mekanik: "Mekanik",
    Benzin: "Benzin",
    people: "3 People",
    img: bvsdfhds,
    desc: "Sport",
  },
  {
    id: "5",
    title: "M3 ",
    category: "Bmw",
    price: "30000",
    mekanik: "Mekanik",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    Button: "1",
    img: cbdetrdy,
    desc: "Sport",
  },
  {
    id: "6",
    title: "M3 ",
    category: "Bmw",
    price: "30000",
    mekanik: "Mekanik",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    Button: "1",
    img: vxcijds,
    desc: "Sport",
  },
  {
    id: "7",
    title: "M3 ",
    category: "Audi",
    price: "30000",
    mekanik: "Mekanik",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    Button: "1",
    img: ihtbsrg,
    desc: "Sport",
  },
  {
    id: "8",
    title: "A3 ",
    category: "Audi",
    price: "30000",
    mekanik: "Mekanik",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    Button: "1",
    img: njuvbewuir,
    desc: "Sport",
  },
  {
    id: "9",
    title: "M3 ",
    category: "Bmw",
    price: "30000",
    mekanik: "Mekanik",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    Button: "1",
    img: sasjdbfgyuas,
    desc: "Sport",
  },
  {
    id: "10",
    title: "M3 ",
    category: "Bmw",
    price: "30000",
    mekanik: "Mekanik",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    Button: "1",
    img: sfhvusr,
    desc: "Sport",
  },
  {
    id: "11",
    title: "M3 ",
    category: "Audi",
    price: "30000",
    mekanik: "Mekanik",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    Button: "1",
    img: sfhdgspkasdfd,
    desc: "Sport",
  },
  {
    id: "12",
    title: "M3 ",
    category: "Bmw",
    price: "30000",
    mekanik: "Mekanik",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    Button: "1",
    img: sfhdg00e93sd,
    desc: "Sport",
  },
  {
    id: "13",
    title: "M3 ",
    category: "Bmw",
    price: "30000",
    mekanik: "Mekanik",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    Button: "1",
    img: sfhdgs47d,
    desc: "Sport",
  },
  {
    id: "14",
    title: "M3 ",
    category: "Bmw",
    price: "30000",
    mekanik: "Mekanik",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    Button: "1",
    img: sfdgvsedhdgsd,
    desc: "Sport",
  },
  {
    id: "15",
    title: "M3 ",
    category: "Audi",
    price: "30000",
    mekanik: "Mekanik",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    Button: "1",
    img: sfhdgdfghesd,
    desc: "Sport",
  },
  {
    id: "16",
    title: "M3 ",
    category: "Bmw",
    price: "30000",
    mekanik: "Mekanik",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    Button: "1",
    img: werbvinsk,
    desc: "Sport",
  },

];

export default Data;