import nRlssF9X from "../imgs/Products/87650_277VIOdLOszxsC2cAzgf6A.jpg";
import sfhdgsd from '../imgs/Products/10018_oVojqO0HUQ_oTMc70bUeYw.jpg';
import fgcxrej from '../imgs/Products/10485_LJGXdzuvcmAJIpXkOK61FA.jpg';
import bvsdfhds from '../imgs/Products/10489_JVg6h65iQHp_g6_NVER0-g.jpg';
import cbdetrdy from '../imgs/Products/11735_T8uBuZKu8bR3XKalDKF82w.jpg';
import vxcijds from '../imgs/Products/20730_XsCaKyvsuCxxeRpjLhebNg.jpg';
import ihtbsrg from '../imgs/Products/29333_nB-qbFD-QGJ_zPxnbmVMCg.jpg';
import njuvbewuir from '../imgs/Products/29430_01fUgtINn_6IYpBwmDZEXw.jpg';
import sasjdbfgyuas from '../imgs/Products/42043_ptG02P2aRd73olzN9cvMwQ.jpg';
import sfhvusr from '../imgs/Products/44044_A1dBpM9bRD-hDQz7IKmJww.jpg';
import sfhdgspkasdfd from '../imgs/Products/51394_6R45tZVPa7QqnBz2tpUH1w.jpg';
import sfhdg00e93sd from '../imgs/Products/51539_Qq133Agpgy56BIY3azi-tw.jpg';
import sfhdgs47d from '../imgs/Products/51544_TZeW3kVicObuC8LKd12-fw.jpg';
import sfdgvsedhdgsd from '../imgs/Products/57687_-No8SPGQDlTvaLVOZyq7hA.jpg';
import sfhdgdfghesd from '../imgs/Products/78230_nRlF9XFVq6pOFOUJUgO9-A.jpg';
import werbvinsk from '../imgs/Products/shadow.jpg';


const Data = [
  {
    id: "4760081600037",
    title: "M3 ",
    category: "Bmw",
    price: "30000",
    year: "2000",
    Ban: "fdfd",
    strPrice: "100.0",
    color: "Qara",
    HP: "500",
    litr: "3L",
    Km: "3000000",
    shassi: "45345343783",
    transmitter: "front",
    Condition: "2.5",
    mekanik: "Mekanik",
    date: "11.05.2020",
    location: "Baku",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    Button: "1",
    img: nRlssF9X,
    desc: "Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.",
  },
  {
    id: "2",
    title: "M3",
    category: "Bmw",
    price: "30000",
    year: "2000",
    Ban: "fdfd",
    strPrice: "100.0",
    color: "dfsf",
    HP: "500",
    litr: "3L",
    Km: "3000000",
    shassi: "NULL",
    transmitter: "front",
    Condition: "3",
    mekanik: "Mekanik",
    date: "11.05.2020",
    location: "Baku",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    Button: "1",
    img: sfhdgsd,
    desc: "Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.",
  },
  {
    id: "3",
    title: "M3 ",
    category: "Audi",
    price: "30000",
    year: "2000",
    Ban: "fdfd",
    strPrice: "100.0",
    color: "dfsf",
    HP: "500",
    litr: "3L",
    Km: "3000000",
    shassi: "NULL",
    transmitter: "front",
    Condition: "5",
    mekanik: "Mekanik",
    date: "11.05.2020",
    location: "Gəncə",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    Button: "1",
    img: fgcxrej,
    desc: "Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.",
  },
  {
    id: "4",
    title: "M3 ",
    category: "Audi",
    price: "30000",
    year: "2000",
    Ban: "fdfd",
    strPrice: "100.0",
    color: "dfsf",
    HP: "500",
    litr: "3L",
    Km: "3000000",
    shassi: "NULL",
    transmitter: "front",
    Condition: "5",
    mekanik: "Mekanik",
    date: "11.05.2020",
    location: "Gəncə",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    Button: "1",
    img: bvsdfhds,
    desc: "Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.",
  },
  {
    id: "5",
    title: "M3 ",
    category: "Bmw",
    price: "30000",
    year: "2000",
    Ban: "fdfd",
    strPrice: "100.0",
    color: "dfsf",
    HP: "500",
    litr: "3L",
    Km: "3000000",
    shassi: "NULL",
    transmitter: "front",
    Condition: "2.5",
    mekanik: "Mekanik",
    date: "11.05.2020",
    location: "Baku",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    Button: "1",
    img: cbdetrdy,
    desc: "Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.",
  },
  {
    id: "6",
    title: "M3 ",
    category: "Bmw",
    price: "30000",
    year: "2000",
    Ban: "fdfd",
    strPrice: "100.0",
    color: "dfsf",
    HP: "500",
    litr: "3L",
    Km: "3000000",
    shassi: "NULL",
    transmitter: "front",
    Condition: "2.5",
    mekanik: "Mekanik",
    date: "11.05.2020",
    location: "Baku",
    Benzin: "Dizel",
    activity: "Active",
    people: "5 People",
    Button: "1",
    img: vxcijds,
    desc: "Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.",
  },
  {
    id: "7",
    title: "M3 ",
    category: "Audi",
    price: "30000",
    year: "2000",
    Ban: "fdfd",
    strPrice: "100.0",
    color: "dfsf",
    HP: "500",
    litr: "3L",
    Km: "3000000",
    shassi: "NULL",
    transmitter: "front",
    Condition: "2.5",
    mekanik: "Mekanik",
    date: "11.05.2020",
    location: "Baku",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    Button: "1",
    img: ihtbsrg,
    desc: "Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.",
  },
  {
    id: "8",
    title: "A3 ",
    category: "Audi",
    price: "30000",
    year: "2000",
    Ban: "fdfd",
    strPrice: "100.0",
    color: "dfsf",
    HP: "500",
    litr: "3L",
    Km: "3000000",
    shassi: "NULL",
    transmitter: "front",
    Condition: "2.5",
    mekanik: "Mekanik",
    date: "11.05.2020",
    location: "Baku",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    Button: "1",
    img: njuvbewuir,
    desc: "Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.",
  },
  {
    id: "9",
    title: "M3 ",
    category: "Bmw",
    price: "30000",
    year: "2000",
    Ban: "fdfd",
    strPrice: "100.0",
    color: "dfsf",
    HP: "500",
    litr: "3L",
    Km: "3000000",
    shassi: "NULL",
    transmitter: "front",
    Condition: "2.5",
    mekanik: "Mekanik",
    date: "11.05.2020",
    location: "Lənkəran",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    Button: "1",
    img: sasjdbfgyuas,
    desc: "Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.",
  },
  {
    id: "10",
    title: "M3 ",
    category: "Bmw",
    price: "30000",
    year: "2000",
    Ban: "fdfd",
    strPrice: "100.0",
    color: "dfsf",
    HP: "500",
    litr: "3L",
    Km: "3000000",
    shassi: "NULL",
    transmitter: "front",
    Condition: "2.5",
    mekanik: "Mekanik",
    date: "11.05.2020",
    location: "Baku",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    Button: "1",
    img: sfhvusr,
    desc: "Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.",
  },
  {
    id: "11",
    title: "Pajero",
    category: "Mitsubishi",
    price: "21 500",
    year: "2007",
    Ban: "Offroader / SUV",
    strPrice: "100.0",
    color: "Qara",
    HP: "189 a.g.",
    litr: "3.0L",
    Km: "183 000",
    shassi: "NULL",
    transmitter: "Tam",
    Condition: "4.8",
    mekanik: "Avtomat",
    date: "11.05.2020",
    location: "Baku",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    Button: "1",
    img: sfhdgspkasdfd,
    desc: "Avtomobıl yaxshı veziyyetdedir    Motor korobka ideal    Vuruq udar yoxdur    Texniki və elektroniki heç bir problemi yoxdur",
  },
  {
    id: "12",
    title: "M3 ",
    category: "Bmw",
    price: "30000",
    year: "2000",
    Ban: "fdfd",
    strPrice: "100.0",
    color: "dfsf",
    HP: "500",
    litr: "3L",
    Km: "3000000",
    shassi: "NULL",
    transmitter: "front",
    Condition: "2.5",
    mekanik: "Mekanik",
    date: "11.05.2020",
    location: "Baku",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    Button: "1",
    img: sfhdg00e93sd,
    desc: "Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.",
  },
  {
    id: "13",
    title: "M3 ",
    category: "Bmw",
    price: "30000",
    year: "2000",
    Ban: "fdfd",
    strPrice: "100.0",
    color: "dfsf",
    HP: "500",
    litr: "3L",
    Km: "3000000",
    shassi: "NULL",
    transmitter: "front",
    Condition: "2.5",
    mekanik: "Mekanik",
    date: "11.05.2020",
    location: "Baku",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    Button: "1",
    img: sfhdgs47d,
    desc: "Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.",
  },
  {
    id: "14",
    title: "M3 ",
    category: "Bmw",
    price: "30000",
    year: "2000",
    Ban: "fdfd",
    strPrice: "100.0",
    color: "dfsf",
    HP: "500",
    litr: "3L",
    Km: "3000000",
    shassi: "NULL",
    transmitter: "front",
    Condition: "2.5",
    mekanik: "Mekanik",
    date: "11.05.2020",
    location: "Baku",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    Button: "1",
    img: sfdgvsedhdgsd,
    desc: "Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.",
  },
  {
    id: "15",
    title: "M3 ",
    category: "Audi",
    price: "30000",
    year: "2000",
    Ban: "fdfd",
    strPrice: "100.0",
    color: "dfsf",
    HP: "500",
    litr: "3L",
    Km: "3000000",
    shassi: "NULL",
    transmitter: "front",
    Condition: "2.5",
    mekanik: "Mekanik",
    date: "11.05.2020",
    location: "Baku",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    Button: "1",
    img: sfhdgdfghesd,
    desc: "Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.",
  },
  {
    id: "16",
    title: "M3 ",
    category: "Bmw",
    price: "30000",
    year: "2000",
    Ban: "fdfd",
    strPrice: "100.0",
    color: "dfsf",
    HP: "500",
    litr: "3L",
    Km: "3000000",
    shassi: "NULL",
    transmitter: "front",
    Condition: "2.5",
    mekanik: "Mekanik",
    date: "11.05.2020",
    location: "Baku",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    Button: "1",
    img: werbvinsk,
    desc: "Avtomobil Almaniyadan yeni gəlib və Azərbaycanda sürülməyib. Bezkraska avtomobildir. Heç bir problemi yoxdur. İstənilen yerdə yoxlada bilərsiz. Avtomobil zavod black editiondir.",
  },

];

export default Data;