const Data = [
  {
    id: "1",
    title: "M3 ",
    category: "Bmw",
    price: "30000",
    people: "5",
    mekanik: "Mekanik",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    img: "/static/media/shadow.e0d0ad4b113a287d911a.jpg",
    desc: "Sport",
  },
  {
    id: "2",
    title: "M3",
    category: "Bmw",
    price: "30000",
    people: "5",
    mekanik: "Mekanik",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    img: "/static/media/87650_277VIOdLOszxsC2cAzgf6A.jpg",
    desc: "Sport",
  },
  {
    id: "3",
    title: "M3 ",
    category: "Audi",
    price: "30000",
    people: "5",
    mekanik: "Mekanik",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    img: "/static/media/78230_nRlF9XFVq6pOFOUJUgO9-A.jpg",
    desc: "Sport",
  },
  {
    id: "4",
    title: "M3 ",
    category: "Bmw",
    price: "30000",
    people: "5",
    mekanik: "Mekanik",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    img: "/static/media/57687_-No8SPGQDlTvaLVOZyq7hA.jpg",
    desc: "Sport",
  },
  {
    id: "5",
    title: "M3 ",
    category: "Bmw",
    price: "30000",
    people: "5",
    mekanik: "Mekanik",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    img: "/static/media/51544_TZeW3kVicObuC8LKd12-fw.jpg",
    desc: "Sport",
  },
  {
    id: "6",
    title: "M3 ",
    category: "Bmw",
    price: "30000",
    people: "5",
    mekanik: "Mekanik",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    img: "/static/media/51539_Qq133Agpgy56BIY3azi-tw.jpg",
    desc: "Sport",
  },
  {
    id: "7",
    title: "M3 ",
    category: "Audi",
    price: "30000",
    people: "5",
    mekanik: "Mekanik",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    img: "/static/media/51394_6R45tZVPa7QqnBz2tpUH1w.jpg",
    desc: "Sport",
  },
  {
    id: "8",
    title: "A3 ",
    category: "Audi",
    price: "30000",
    people: "5",
    mekanik: "Mekanik",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    img: "/static/media/44044_A1dBpM9bRD-hDQz7IKmJww.jpg",
    desc: "Sport",
  },
  {
    id: "9",
    title: "M3 ",
    category: "Bmw",
    price: "30000",
    people: "5",
    mekanik: "Mekanik",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    img: "/static/media/42043_ptG02P2aRd73olzN9cvMwQ.jpg",
    desc: "Sport",
  },
  {
    id: "10",
    title: "M3 ",
    category: "Bmw",
    price: "30000",
    people: "5",
    mekanik: "Mekanik",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    img: "/static/media/29333_nB-qbFD-QGJ_zPxnbmVMCg.jpg",
    desc: "Sport",
  },
  {
    id: "11",
    title: "M3 ",
    category: "Audi",
    price: "30000",
    people: "5",
    mekanik: "Mekanik",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    img: "/static/media/20730_XsCaKyvsuCxxeRpjLhebNg.jpg",
    desc: "Sport",
  },
  {
    id: "12",
    title: "M3 ",
    category: "Bmw",
    price: "30000",
    people: "5",
    mekanik: "Mekanik",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    img: "/static/media/11735_T8uBuZKu8bR3XKalDKF82w.jpg",
    desc: "Sport",
  },
  {
    id: "13",
    title: "M3 ",
    category: "Bmw",
    price: "30000",
    people: "5",
    mekanik: "Mekanik",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    img: "/static/media/10489_JVg6h65iQHp_g6_NVER0-g.jpg",
    desc: "Sport",
  },
  {
    id: "14",
    title: "M3 ",
    category: "Bmw",
    price: "30000",
    people: "5",
    mekanik: "Mekanik",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    img: "/static/media/10485_LJGXdzuvcmAJIpXkOK61FA.jpg",
    desc: "Sport",
  },
  {
    id: "15",
    title: "M3 ",
    category: "Audi",
    price: "30000",
    people: "5",
    mekanik: "Mekanik",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    img: "src/imgs/Products/10018_oVojqO0HUQ_oTMc70bUeYw.jpg",
    desc: "Sport",
  },
  {
    id: "16",
    title: "M3 ",
    category: "Bmw",
    price: "30000",
    people: "5",
    mekanik: "Mekanik",
    Benzin: "Benzin",
    activity: "Active",
    people: "5 People",
    img: "/static/media/29430_01fUgtINn_6IYpBwmDZEXw.jpg",
    desc: "Sport",
  },

];

export default Data;